docassemble/VirtualCourtToolbox/data/static/textDateInput.js
Spacing looks strange because the code uses tabs instead of spaces. I can fix that on another go around.
Not sure why git thinks that everything's been replaced.
=> Remove the behavior of altering user entered dates when invalid

docassemble/VirtualCourtToolbox/ThreePartDateDataType.py, docassemble/VirtualCourtToolbox/data/static/textDateInput.js, docassemble/VirtualCourtToolbox/shortenURL.py
We can move the js into here as well so that we don't have to include as many files. I just didn't want to do it at the same time.
Also, keeping the date validation function in `.misc` might be a useful toolbox tool, so I left it where it was. Would appreciate thoughts on that.
=> Validate in `CustomDataType` instead of in YAML. Delete unused file.

LICENSE, docassemble/ALToolbox/ThreePartsDate.py, docassemble/ALToolbox/data/questions/ThreePartsDate.yml
Closes #44.
Sorry that GitHub is doing such a bad job of showing when changes are just whitespace changes. It was just easier for me to read with some indentation tweaks.
I would appreciate some testing on this. To test this, you'll have to edit the files and change the customdatatype names in the .py and the .yml because they could otherwise be overridden by our current customdatatypes. For me, they were overridden. I dealt with it by adding "Foo" before the names.
=> Allow an empty date field to be valid when the answer is not required

.gitignore, docassemble/ALToolbox/misc.py
Issue was caught by aXe-core testing: https://dequeuniversity.com/rules/axe/4.4/aria-valid-attr-value?application=axe-puppeteer
The issue happened because `tag_group_name` was added to the beginning of each id / href, but not to aria-controls.
The `tab_id` was never used individually, so I just updated it to include both `tab_group_name` and `tab_id`,
and then replaced its used in the tabs and tab panels.
=> Correct `aria-controls` to refernce correct id

docassemble/ALToolbox/misc.py
Ran into this when I tried to have the contents of a collapse-able template vary on some other variables in the interview (only showing IL specific information to fill in a case number when the jurisdiction was IL). IMO returning an empty string instead of a drop down with nothing in the title or body is probably better.
=> Return empty str if template is blank

.gitignore, docassemble/ALToolbox/business_days.py, docassemble/ALToolbox/test_altoolbox.py
The existing code didn't seem to work with DADateTime objects because it was expecting dates formatted like `%m/%d/%Y`. Switched to using ISO date formats throughout and simplified the logic a bit. I'm not sure if the `non_business_days()` function is strictly needed but I left that basically alone for now as it's not necessary to the core functionality.
A simple test YAML to explore:
```yaml
modules:
- .business_days
---
question: |
What date do you want to check?
fields:
- Date: the_date
datatype: date
---
mandatory: True
question: |
% if is_business_day(the_date):
${ the_date } is a business day
% else:
${ the_date } is NOT a business day
The next business day is ${ get_next_business_day(the_date) }
% endif
```  
@purplesky2016 feel free to ignore but figured this was your baby and I …
=> Business day normalize date strings

.github/workflows/unit-tests.yml, docassemble/ALToolbox/al_income.py, docassemble/ALToolbox/misc.py, docassemble/ALToolbox/requirements.txt, docassemble/ALToolbox/save_input_data.py, docassemble/ALToolbox/test_al_income.py, docassemble/ALToolbox/test_altoolbox.py, mypy.ini
* Decimal floating point rep errors (fixes #99)
Get the locale's `frac_digits`, which is the number of fractional digits in currency, and always rounds to it when using floats. This is safe if being used on inputs from docassemble's `currency` datatype, which truncates the user typed value to that number of digits (but still stores it in a float).
Some notable examples of locales that don't use 2 digits of fractional currency (from [Locale Helper](https://lh.2xlibre.net/values/frac_digits/)):
* all arabic locales use 3 digits
* Japan, Korea, and Iceland use 0 digits (i.e. all round numbers)
* `total()` in itemized job not working:
Was iterating over the dictionary itself, which just gives the keys (i.e. the sources / names), not the item itself. Didn't error because we're checking …
=> Fixed bugs in ALIncome:

.gitignore, docassemble/ALToolbox/data/questions/collapse_template_demo.yml, docassemble/ALToolbox/misc.py
Fix #115
Adds two new keyword parameters to `collapse_template`: `expand_icon` and `collapse_icon` which are assumed to be fontawesome icons in the "fa-solid" category. 
Also updated `fa_icon()` to use new Fontawesome 5 `fa-solid` class explicitly instead of the deprecated `fa` class.
=> Make icons configurable for `collapse_template()`

docassemble/ALToolbox/al_income.py, docassemble/ALToolbox/data/questions/al_income.yml, docassemble/ALToolbox/data/questions/al_income_demo.yml
* Made the ALPeriodicAmount class. Which is solely intended to house duplicate code between `ALExpense` and `ALIncome`. It straightens out the class hierarchy a bit, but it shouldn't be a concern for anyone but us, the module maintainers.
* adds the `move_checks_to_list`, to standardize the preferred way of gathering a big long list of potential expenses or incomes: by taking a checkboxes variable on a object and turning it into elements in a list with the `source` the same as the checkbox value
* made the ALJob class closer to the ALItemizedJob class. They shouldn't be different except for the Itemized part, so I made the employee an Individual
* Added the ALExpense and ALExpenses classes, as discussed previously (to avoid using the ALItemizedValueDict class)
* made slightly better names …
=> More income module changes

docassemble/ALToolbox/data/questions/al_income.yml
Asking only if an ItemizedValueDict entry exists won't ask the user the right questions; specifically letting them change the value of their dict. In this case, I've been setting up interviews to automatically define `exists` if asked for in this way, since usually I've been using `move_checks_to_list` to make objects already exist, yes / no. This means having `exists` and `value` re-edited doesn't ask two questions of the user.
Additionally, adds a default `revisit` question for the ALIncomeList object; otherwise edit buttons on review screens do nothing. 
Have tested with Affidavit Supplement, will likely merge without review, but feel free to give one post merge.
=> Redefine the value of an item, not if it exists

docassemble/ALToolbox/misc.py
Was pointing to "collapseExample". Should now point to the correct ID of the collapsed element.
=> Make aria-controls point to a real element

docassemble/ALToolbox/data/questions/al_income.yml
Currently being used for jobs of other household members in the Affidavit of Indigency supplement.
I did make a choice to ask for `net` in the ALJob upon edit. Might considering adjusting that API: how do / will most authors use ALJob? Do they need to know both net and gross, without knowing a specific deduction? Or given a specific job, will it always be gross or net? Might be a different PR.
=> Add ALJobList revisit and table screens

docassemble/ALToolbox/ThreePartsDate.py
We've seen some errors in DA, where formatting a date into a string tries to get info from the current thread (the interview title?!) that it doesn't have, and will error. This should fix that issue, but just showing the date ppl gave to us.
Keeping this draft until I can:
* recreate the issue on apps-dev
* confirm that this branch fixes the issue
=> ThreePartDate: put str in error message, not date

docassemble/ALToolbox/copy_button.py, docassemble/ALToolbox/misc.py
Some great documentation for the functions had been written in the documentation site, and IMO it should live a bit closer to the functions themselves. I moved over what I could, and updated old docs where I saw them.
Will merge without review, since it's just documentation. Feel free to review post-merge.
=> Update docstrings in misc and copy_button

docassemble/ALToolbox/al_income.py, docassemble/ALToolbox/data/questions/al_income.yml
We had `input type: number`, which doesn't exist, and so was doing nothing. Changed to `datatype: number`, and added validation messages that should show if the user enters something that's not a number.
=> Enforce people entering numbers for hours

docassemble/ALToolbox/data/questions/al_income.yml, docassemble/ALToolbox/data/questions/al_income_demo.yml
for ALExpenseList. Additionally, removes `complete_attribute="exists"` from the income demo expense list, as it's not needed, and can cause issues with review screens.
This is an upstream fix for an issue also fixed in https://github.com/SuffolkLITLab/docassemble-ALAffidavitOfIndigency/pull/49.
=> Update display_name when category is changed

docassemble/ALToolbox/Addup.py, docassemble/ALToolbox/PhoneNumberDataType.py, docassemble/ALToolbox/ThreePartsDate.py, docassemble/ALToolbox/addenda.py, docassemble/ALToolbox/copy_button.py, docassemble/ALToolbox/display_template.py
Making this change because a giant string js_text is getting loaded into the answers of every interview that uses ThreePartsDate or BirthDate right now; this should stop that. Also a good practice for every module.
=> Add __all__ to all modules

docassemble/ALToolbox/copy_button.py
Ran into this when using the Dashboard review generator, and there was an extra quote at the end of the last block. Isn't necessary, and makes the resulting DA YAML have a subtle bug.
Will test on dev, and remove if it fixes the issue.
=> Remove unnecessary quote

docassemble/ALToolbox/data/static/collapse_template.css
In dark mode, the display templates still have a light background, causing contrast issues with the text inside, and in general stands out far too much against the page background. This adds CSS to change the `bg-light` class for the collapse and display templates to the dark-mode colors when `data-bs-theme=dark`.
See https://github.com/jhpyle/docassemble/pull/718 for a discussion on a suggested fix for a similar issue, which resulted in the suggested workaround here.
An image of the dark mode display template without this PR:
An image of the dark mode display template with this PR:
=> Make collapse/display templates work in dark mode

docassemble/ALToolbox/misc.py, docassemble/ALToolbox/test_misc.py
fix #218
This is a better way to create index/menu pages that show various features, like the Dashboard's menu of tasks.
Sample:
```yaml
---
modules:
- .misc
---
mandatory: True
question: |
subquestion: |
${ button_array([{"url": "http://example.com", "name": "Example", "image": "earth-americas"}, {"url": "http://example.com", "name": "Example", "privilege": ["crazy pants", "admin"], "image": "link"}, {"url": "http://example.com", "name": "Example", "image": "map"}], custom_link_class="text-primary bg-warning") }
```
Going to merge as this is new code that's low risk.
=> Add button_array function

.github/workflows/unit-tests.yml, docassemble/ALToolbox/test_al_income.py
Which has 3 decimal places, testing a bit more of our currency locale handling code, besides just the US.
Fix #104.
=> Add tests for the arabic locale

docassemble/ALToolbox/data/static/collapse_template.css
They serve the same function (tap to get more information, and they don't navigate you away from the page), so it makes sense to brand them the same.
I'm not quite used to it yet, but I do think I will with a bit of time. Also have to keep in mind that most users aren't coming back again and again, they use our side a few times and don't return.
Fixes #208
=> Make display_template look like a daterm

docassemble/ALToolbox/data/questions/escape_button.yml, docassemble/ALToolbox/data/questions/escape_button_demo.yml
There wasn't a list to contain the escape button, so it shouldn't be a list item.
Also fixed some display issues on the demo page (three backticks for code blocks doesn't seem to work anymore).
Fix #196.
=> Change the escape button tag to a div, not a li

docassemble/ALToolbox/ThreePartsDate.py, setup.py
Closes #214. No rush on my part. I've tested it a bit myself to make sure basic behavior hasn't changed, though I don't think I have the tools I need to test the accessibility properly.
Not sure if we want to increment those package versions.
=> Improve accessibility by associating `for` with `id` instead of `name`

docassemble/ALToolbox/data/questions/al_income.yml, docassemble/ALToolbox/data/questions/al_income_demo.yml
Can't do much more, but we can kind make them look not like variables|
Need to test, I'll merge once I have
#191
=> Get rid of underscores in ItemizedValueDict table

docassemble/ALToolbox/data/questions/display_template_demo.yml, docassemble/ALToolbox/display_template.py
Addition onto #208, which should have fixed this for collapsible display templates too, but didn't because they didn't use the same classes, for no reason that I can see: `al_toggle` wasn't used in style sheets before #232.
Have already tested, going to merge.
=> Styles for display template

docassemble/ALToolbox/data/questions/chat_completion_demo.yml, docassemble/ALToolbox/data/questions/goal_satisfy.yml, docassemble/ALToolbox/data/questions/goal_satisfy_demo.yml, docassemble/ALToolbox/llms.py, docassemble/ALToolbox/requirements.txt
Fix #236 
Fix #239 
Fix #238 
This provides a wrapper and demos around some common tasks with large language models and gives them a Docassemble API:
1. Prompt => get back transformed text (e.g., translate, make plain language, turn into a poem, etc.)
2. Extract fields from unstructured text and define them in the interview's name space
3. Create an interactive dialogue with a user (e.g., ask follow-up questions) until a goal is met. For example: to help someone draft a compelling affidavit that meets all aspects of a legal claim
=> Add a basic wrapper around GPT-3.5/GPT-4 API

docassemble/ALToolbox/llms.py
Avoids errors in logs like:
```
Import of docassemble.ALToolbox.llms failed.
OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```
=> If no openai key, don't try to make an OpenAI obj

docassemble/ALToolbox/ThreePartsDate.py
https://github.com/SuffolkLITLab/docassemble-ALToolbox/pull/241 introduced a slight regression that assumed that both `alMax` and `alMin` would be present. If they weren't, the JS on the page would stop running, resulting in error messages not going away even when corrected.
Tested on my local server and it fixed the problem, removing the errors in my browser console.
Fix #244
=> Fixed bug that required alMax

docassemble/ALToolbox/data/questions/al_income.yml
=> Close #243, remove redundant `x.to_subract` code

docassemble/ALToolbox/ThreePartsDate.py
Finish the code done in https://github.com/SuffolkLITLab/docassemble-ALToolbox/pull/245.
@plocket, is this the direction we want to take? I tried a version using `if/else`s like you suggested in https://github.com/SuffolkLITLab/docassemble-ALToolbox/pull/245#discussion_r1453649722, but there are more cases than you mentioned there. It was much harder to read IMO, so I didn't continue that.
This does treat invalid alMax / alMin dates as nothing instead of as a NaN Date, which will always be false when compared to other dates with `<=` and `>=`. I think means user's wouldn't be able to submit? (part of the testing I need to still do). It's a behavior change, but probably the safest one?
Tested with:
=> Check isNaN on alMax & use today as birthdate max

docassemble/ALToolbox/business_days.py, docassemble/ALToolbox/llms.py
Fix #254
For speed and efficiency, automators may want to skip the moderation endpoint that is usually called by the chat_completion function. All queries are moderated by default as a best practice to avoid the account being flagged, but if you **know** the query is safe, this change allows you to skip it.
Also removed some logging statements that could have slowed down performance.
=> Make moderation optional in llms.py, remove references to gpt-4-turbo-1106-preview as json mode is now general release

docassemble/ALToolbox/misc.py, docassemble/ALToolbox/test_misc.py
Fix #263
This pull request introduces three new utility functions to enhance template handling and prevent unwanted placeholder text (e.g., "None" or "Other") from appearing in the output. These functions are designed to help write more readable template code.
```python
def none_to_empty(val: Any):
"""If the value is None or "None", return a DAEmpty value. Otherwise return the value."""
```
* Purpose: Replaces None or the string "None" with a DAEmpty value to ensure that these placeholders do not appear in the final output.
* Use Case: Particularly useful when handling optional fields, such as radio buttons that may not be selected.
```python
def option_or_other(
variable_name: str, other_variable_name: Optional[str] = None
) -> str:
"""If the variable is set to 'Other', return the value …
```
=> Add a few utility functions for DOCX templates - handle None values and Other for checkboxes and radio buttons

.github/workflows/unit-tests.yml, docassemble/ALToolbox/misc.py
Tests are currently not passing because of a breaking change in Docassemble 1.6 that only affects the test, not the runtime (tests aren't able to discover the docassemble.base package).
=> Add 'include_a_year' helper function for validation of free-text date fields

docassemble/ALToolbox/misc.py
I wanted to be able to have a collapse_template() that is initially un-collapsed that the user could collapse themselves.
=> feat: add new arg `collapsed` to collapse_template() to allow un-collapsed initial appearance; updated type hints

setup.py
Using the currently installed version of both packages from apps-dev.suffolklitlab.org
We have other similar one-off dependencies installed for features someone might or might not decide to use, so I think these make sense, too.
=> Add dependencies for llms.py
